const recipes = [
  {
    recipeid: 199448,
    name: "Ww Vegetarian Chili",
    description:
      "I got this from a community recipe swap years ago. It is rich in flavor and only 1 point per serving. You can add any additional 0 point vegetables in it or ground turkey and adjust the points. This is one of my WW favorites",
    images: "character(0)",
    recipecategory: "Black Beans",
    keywords: ["Onions", "Peppers", "Beans", "Vegetable", "< 60 Mins", "Easy"],
    recipeingredientquantities: [
      "1",
      "3",
      "1",
      "1",
      "1",
      "1",
      "6",
      "2",
      "1",
      "1",
      "NA",
      "NA",
    ],
    recipeingredientparts: [
      "chicken broth",
      "Rotel tomatoes & chilies",
      "celery",
      "onion",
      "hot salsa",
      "pinto beans",
      "black beans",
      "chili powder",
    ],
    recipeservings: 8.0,
    recipeinstructions: [
      "Mix all ingredients in a large stew pot. Cook for 30-45 minutes.",
    ],
    cooktimeamt: "30",
    cookunitoftime: "M",
    preptimeamt: "10",
    prepunitoftime: "M",
    totalhours: "40",
    totalminutes: null,
    christmas: 0,
    thanksgiving: 0,
    hannukah: 0,
    nye: 0,
    breakfast: 0,
    lunch: 0,
    dessert: 0,
    dinner: 1,
  },
  {
    recipeid: 460679,
    name: "Creamy Coleslaw (My Version of Deer Head Inn)",
    description:
      "The former Deer Head Inn in Spring Creek PA served the most delicious coleslaw and I have tried to replicate it.  I made coleslaw tonight and am saving it here because this is as close as I have ever come to matching it.",
    images: "character(0)",
    recipecategory: "Vegetable",
    keywords: ["< 4 Hours", "Easy"],
    recipeingredientquantities: [
      "1",
      "4",
      "3/4 - 1",
      "2",
      "2",
      "2",
      "1/4",
      "1/4",
      "NA",
    ],
    recipeingredientparts: [
      "green onions",
      "mayonnaise",
      "sugar",
      "vinegar",
      "half-and-half",
      "celery seed",
    ],
    recipeservings: 8.0,
    recipeinstructions: [
      "Combine coleslaw mix and diced onions in a large bowl.",
      "In a separate bowl",
      "combine remaining ingredients with a whisk until smooth.",
      "Mix dressing into coleslaw and adjust seasonings as desired.",
      "Refrigerate at least 1 hour.",
    ],
    cooktimeamt: "1",
    cookunitoftime: "H",
    preptimeamt: "10",
    prepunitoftime: "M",
    totalhours: "1",
    totalminutes: "10",
    christmas: 0,
    thanksgiving: 0,
    hannukah: 0,
    nye: 0,
    breakfast: 0,
    lunch: 0,
    dessert: 0,
    dinner: 1,
  },
];

module.exports = recipes;
